### ISSUE TITLE
Librato Script

### ISSUE THREAD

**Issue by freshkurt** [codeship/scripts#11]
Provide a shellscript to add deployment annotations to Librato according to their documentation on http://support.metrics.librato.com/knowledgebase/articles/122410-adding-annotations-to-graphs

All required configuration shall be done via environment variables and there should be default values where it makes sense.  Include at least a link to the build on Codeship and set the description to the commit message.

Reach out to marko@codeship.com if you have any questions!

**Comment by mlocher** [comment]
Closed via #54
