### ISSUE TITLE
fatal: --unshallow on a complete repository does not make sense

### ISSUE THREAD

**Issue by mderazon** [codeship/scripts#114]
when running this:
https://github.com/codeship/scripts/blob/master/deployments/git_push.sh#L17

**Comment by mlocher** [comment]
The cloned repositories on Codeship only checkout the last 50 commits. This might be the full history for smaller projects, but older/bigger repositories run into error regarding the shallow clone.

Plus the overhead from running the unshallow on a fully cloned repository is pretty small imo.

**Comment by mderazon** [comment]
I'm curious, why checkout previous commits at all ?

**Comment by mlocher** [comment]
Some builds require a bit more history available. Some git based deployments work without unshallowing as well, it depends on how often you deploy (and your git version).

**Comment by sethbergman** [comment]
I believe the PR I submitted awhile back would take care of your issue. 
[Added Dokku Deployment Script #106](https://github.com/codeship/scripts/pull/106)
