### ISSUE TITLE
New Relic Script

### ISSUE THREAD

**Issue by freshkurt** [codeship/scripts#12]
Adapt the already included [notification script](/codeship/scripts/blob/master/notifications/new_relic.sh) to handle the issues mentioned on https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/setting-deployment-notifications#deployment_limits, especially

> - Do not include line breaks or carriage returns. These will cause errors or fail to report.
> - Do not include a semicolon ; in the character string. Semicolons denote the end of a line in the CLI and your command will be truncated.

which can be included in the commit message and other fields as well.

**Comment by mlocher** [comment]
This was added in #52
