### ISSUE TITLE
[MongoDB] Faster CI

### ISSUE THREAD

**Issue by mathieug** [codeship/scripts#181]
MongoDB gives some tips to faster its usage in a CI: [Webinar: Continuous Integration with Node.JS and MongoDB](https://www.slideshare.net/mongodb/10-24-continuous-integration-with-nodejs-and-mongo-db/24)

I'll try those three parameters and I'll submit a PR. I don't know if it's really efficient, maybe a benchmark could tell us.

**Comment by joesiewert** [comment]
Closing this out due to the age of the issue. Feel free to submit a PR if you find some better settings though. 😄
