### ISSUE TITLE
Uploading artifacts to google cloud compute engine vm

### ISSUE THREAD

**Issue by johnmelba** [codeship/scripts#2]
I'm looking into https://github.com/codeship/scripts/blob/google-cloud-sdk/packages/google_cloud_sdk.sh

All these steps worked for me. The next step for me is to upload the artifact and run some commands via ssh. I tried following 
1. gcloud compute copy-files --quiet <artifact>  <instance>:/tmp/ --zone us-central1-a
2. It tries to generate the ssh key and waits for passphrase
3. gcutil push <instance> <artifact> /tmp
4. Resp is same as 1

3 .rm -rf ~/.ssh/google_compute_engine*
/usr/bin/ssh-keygen -q -f ~/.ssh/google_compute_engine -N ""
gcloud compute config-ssh --quiet
scp <artifact> <instance>:/tmp
- SCP waits forever.. 

How can I upload artifact and run ssh commands?

**Comment by joesiewert** [comment]
Closing this out due to the age of the issue. Please reach out to support@codeship.com for assistance.

The gcloud CLI is now installed in the Codeship Basic environment:  https://documentation.codeship.com/basic/continuous-deployment/deployment-with-gcloudcli
