### ISSUE TITLE
update node and npm version .

### ISSUE THREAD

**Issue by vamshi9666** [codeship/scripts#214]
when i triggered my react project , i saw a thousand warnings saying that `node` version is required `>=5` but existing `node` version is `0.10`.
being older version of node . it was not able to install newer packages with new `node` support .

**Comment by joesiewert** [comment]
Hi @vamshi9666, you should be able to specify the Node version either with `nvm` or by specifying the version in your `package.json` file.

https://documentation.codeship.com/basic/languages-frameworks/nodejs

Let us know at support@codeship.com if that is not working for you and we can take a closer look.

**Comment by vamshi9666** [comment]
I tried to install `npm` with `npm install -g npm`  it didn't work.

**Comment by mlocher** [comment]
Could you head over to https://helpdesk.codeship.com and open a ticket. Please provide a link to the failing build so we can look into this and help you resolve this.

**Comment by vamshi9666** [comment]
@joesiewert . i solved my issue by using nvm .
i recommend to include that in starting docs of codeship. so thta every codeshipper can know it in starting itself

**Comment by mlocher** [comment]
Ahoy @vamshi9666, we do include that information on https://documentation.codeship.com/basic/languages-frameworks/nodejs/#versions-and-setup as well as in the default setup and test commands for Node.js

We'll take another look at the documentation and the command templates and see how we can improve them.

**Comment by vamshi9666** [comment]
thank you for rapid and helpful response @mlocher

**Comment by mlocher** [comment]
Of course, we're always working on making Codeship a better product than it is right now (though we definitely think it's already a great product 😄) and feedback like yours is very valuable to us. So thank you for taking the time to reach out and bring this up, this is great!
