### ISSUE TITLE
eb_deployment_check is missing

### ISSUE THREAD

**Issue by peterlada** [codeship/scripts#222]
`eb_deployment_check` is used in the script for elastic beanstalk deployment, yet it is not published here.

**Comment by joesiewert** [comment]
@peterlada, thanks for catching this. You can find a copy of that here: https://github.com/codeship-library/aws-utilities/blob/master/deployment/scripts/eb_deployment_check

**Comment by joesiewert** [comment]
Added in https://github.com/codeship/scripts/pull/224
