### ISSUE TITLE
Suggest excluding tmp directory in zip file

### ISSUE THREAD

**Issue by scott** [codeship/scripts#223]
In `scripts/deployments/elastic_beanstalk.sh` the script packages the `tmp` directory for Rails projects into the `.zip` that is pushed to EB. This can deploy test run artifacts and cache fragments to production if they are not completely cleaned after the test run, which I don't think is the default test behavior.  It would be wise to exclude this directory from being uploaded.

**Comment by joesiewert** [comment]
Thanks for the feedback @scott. We will look at incorporating this and also replied to you in greater detail via Zendesk.
