### ISSUE TITLE
Need Scripts to automate Salesforce deployment

### ISSUE THREAD

**Issue by VickalGupta** [codeship/scripts#240]
I tried to find Scripts for CodeShip to automate Salesforce deployment process using ANT, but couldn't find much. Any help on this will be very helpful.

**Comment by joesiewert** [comment]
@VickalGupta we don't have any custom scripts in here for Salesforce, but you should have full access on the build machine to run any setup/install commands needed (including `sudo`). You can reach out to support@codeship.com with more details and we can work on it from there as well.

**Comment by swagattalsania** [comment]
Hi @VickalGupta. Did you figure out how to make it work? My team has a similar scenario which they would like to automate.

**Comment by swagattalsania** [comment]
Found this post: https://www.zencloudtech.com/continuous-deployment-in-salesforce-github-bitbucket-codeship/
