### ISSUE TITLE
Mysql 8.0 script does not handle 206 Partial Content when downloading mysql package 

### ISSUE THREAD

**Issue by zlailari** [codeship/scripts#267]
As part of our test setup commands, we run `curl -sSL https://raw.githubusercontent.com/codeship/scripts/master/packages/mysql-8.0.sh | bash -s`

We are seeing intermittent failures when the mysql CDN responds with a `206 Partial Content` and the `wget` (despite the `--continue` flag) doesn't complete the download in the default 20 retries. [Here's a gist with the output](https://gist.github.com/zlailari/6e8419e0fd745f8a0e75761e8c547560)

Let me know if I can provide any additional information!

**Comment by joesiewert** [comment]
@zlailari about how often do you see this in your builds?

**Comment by zlailari** [comment]
About 10%

**Comment by joesiewert** [comment]
What about hosting that source file on S3 (or similar) and grabbing from there instead?

**Comment by zlailari** [comment]
It's downloading consistently with the file hosted in S3

**Comment by joesiewert** [comment]
Awesome!
