### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by mrz1836** [codeship/scripts#96]
scripts/languages/go.sh
line: 28

check the correct version is **yused**

Should be:

check the correct version is **used**

**Comment by jasonsouza** [comment]
Thanks for catching the spelling error we made. Would you be interested in creating a PR to receive contribution credit?

**Comment by mrz1836** [comment]
I appreciate it - but I'm going to pass :-)

I've got a lot of work to do - just trying to help!

**Comment by mlocher** [comment]
@mrz1836 No worries, totally understandable. The PR is ready, waiting on review right now (don't start skipping that, even for trivial changes).

Thanks again for spotting this and letting us know 👍
